// gap_filler_sm100.cu — fill encoding gaps for SM_100/SM_103 repos.
// Targets opcodes missing from the initial repos build.
// Build: nvcc -O0 -std=c++17 -lineinfo -gencode arch=compute_103a,code=sm_103a -cubin gap_filler_sm100.cu
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <cstdint>

// ================================================================
// BFE — bitfield extract
// ================================================================
__device__ __noinline__ unsigned bfe_ops(unsigned a, unsigned b, unsigned c) {
    unsigned r1, r2, r3, r4;
    asm volatile("bfe.u32 %0, %1, 0, 8;" : "=r"(r1) : "r"(a));
    asm volatile("bfe.u32 %0, %1, 4, 12;" : "=r"(r2) : "r"(b));
    asm volatile("bfe.s32 %0, %1, 8, 16;" : "=r"(r3) : "r"(c));
    asm volatile("bfe.u32 %0, %1, %2, %3;" : "=r"(r4) : "r"(a), "r"(b), "r"(c));
    return r1 + r2 + r3 + r4;
}

// ================================================================
// BFI — bitfield insert
// ================================================================
__device__ __noinline__ unsigned bfi_ops(unsigned a, unsigned b, unsigned c) {
    unsigned r1, r2, r3;
    asm volatile("bfi.b32 %0, %1, %2, 0, 8;" : "=r"(r1) : "r"(a), "r"(b));
    asm volatile("bfi.b32 %0, %1, %2, 4, 12;" : "=r"(r2) : "r"(b), "r"(c));
    asm volatile("bfi.b32 %0, %1, %2, %3, %4;" : "=r"(r3) : "r"(a), "r"(b), "r"(c), "r"(8u));
    return r1 + r2 + r3;
}

// ================================================================
// DMNMX — FP64 min/max
// ================================================================
__device__ __noinline__ double dmnmx_ops(double a, double b) {
    return fmin(a, b) + fmax(a, b);
}

// ================================================================
// FMNMX3, IMNMX3 — 3-input min/max (SM_100 new)
// Compiler may or may not emit these; force via nested calls at O2
// ================================================================
__device__ __noinline__ float fmnmx3_ops(float a, float b, float c) {
    float mn = fminf(fminf(a, b), c);
    float mx = fmaxf(fmaxf(a, b), c);
    return mn + mx;
}

__device__ __noinline__ int imnmx3_ops(int a, int b, int c) {
    int mn = min(min(a, b), c);
    int mx = max(max(a, b), c);
    return mn + mx;
}

// ================================================================
// JMP — indexed branch (via switch with many cases)
// ================================================================
__device__ __noinline__ int jmp_ops(int x) {
    switch (x & 0xf) {
        case 0: return x * 2;
        case 1: return x + 100;
        case 2: return x - 50;
        case 3: return x * 3;
        case 4: return x + 200;
        case 5: return x - 100;
        case 6: return x * 4;
        case 7: return x + 300;
        case 8: return x - 150;
        case 9: return x * 5;
        case 10: return x + 400;
        case 11: return x - 200;
        case 12: return x * 6;
        case 13: return x + 500;
        case 14: return x - 250;
        default: return x;
    }
}

// ================================================================
// LDU — load uniform (read-only texture/const path)
// ================================================================
__device__ __noinline__ float ldu_ops(const float* __restrict__ p, int idx) {
    float r;
    asm volatile("ldu.global.f32 %0, [%1];" : "=f"(r) : "l"(p + idx));
    return r;
}

// ================================================================
// MBAR — mbarrier operations
// ================================================================
__device__ __noinline__ void mbar_ops(unsigned long long* smem_mbar) {
    unsigned mbar_addr = (unsigned)(uintptr_t)smem_mbar;
    asm volatile(
        "mbarrier.init.shared::cta.b64 [%0], 1;\n\t"
        :: "r"(mbar_addr) : "memory");
    asm volatile(
        "mbarrier.arrive.shared::cta.b64 _, [%0];\n\t"
        :: "r"(mbar_addr) : "memory");
    asm volatile(
        "mbarrier.arrive.expect_tx.shared::cta.b64 _, [%0], 128;\n\t"
        :: "r"(mbar_addr) : "memory");
    asm volatile(
        "{\n\t"
        ".reg .pred p;\n\t"
        "mbarrier.test_wait.parity.shared::cta.b64 p, [%0], 0;\n\t"
        "}\n\t"
        :: "r"(mbar_addr) : "memory");
    // mbarrier.invalidate requires sm_90a; skip
}

// CCTLL — cache control (local) — generated by compiler automatically

// ================================================================
// UTMACPL / UTMASTG / UTMAPF / UTMRPL — TMA operations
// These need tensormap descriptors; compile-only verification.
// ================================================================
extern "C" __global__ void k_tma_ops(void* smem_ptr, const void* tmap_ptr,
                                      unsigned long long* mbar_ptr) {
    unsigned smem = (unsigned)(uintptr_t)smem_ptr;
    unsigned mbar = (unsigned)(uintptr_t)mbar_ptr;

    // UTMACPL — TMA tile load (1D)
    asm volatile(
        "cp.async.bulk.tensor.1d.shared::cta.global.tile"
        ".mbarrier::complete_tx::bytes [%0], [%1, {%2}], [%3];\n\t"
        :: "r"(smem), "l"(tmap_ptr), "r"(0), "r"(mbar) : "memory");

    // UTMACPL — TMA tile load (2D)
    asm volatile(
        "cp.async.bulk.tensor.2d.shared::cta.global.tile"
        ".mbarrier::complete_tx::bytes [%0], [%1, {%2, %3}], [%4];\n\t"
        :: "r"(smem), "l"(tmap_ptr), "r"(0), "r"(0), "r"(mbar) : "memory");

    // UTMASTG — TMA store (1D)
    asm volatile(
        "cp.async.bulk.tensor.1d.global.shared::cta.tile.bulk_group"
        " [%0, {%1}], [%2];\n\t"
        "cp.async.bulk.commit_group;\n\t"
        "cp.async.bulk.wait_group 0;\n\t"
        :: "l"(tmap_ptr), "r"(0), "r"(smem) : "memory");

    // UTMAPF — TMA prefetch (1D)
    asm volatile(
        "cp.async.bulk.prefetch.tensor.1d.L2.global.tile"
        " [%0, {%1}];\n\t"
        :: "l"(tmap_ptr), "r"(0) : "memory");

    // UTMRPL — tensormap replace
    asm volatile(
        "tensormap.replace.tile.global_address.shared::cta.b1024.b64"
        " [%0], %1;\n\t"
        :: "r"(smem), "l"((unsigned long long)0x1000) : "memory");

    asm volatile(
        "tensormap.replace.tile.rank.shared::cta.b1024.b32"
        " [%0], %1;\n\t"
        :: "r"(smem), "r"(2) : "memory");
}

// UTMACCTL — TMA cache control — generated automatically by TMA prefetch ops above

// UCLCTL — cluster launch control requires complex cluster setup,
// skip for now (encoding can be obtained from CUTLASS cubins)

// ================================================================
// tcgen05 sync operations: UTCFENCE, UTCCOMMIT, UTCWAIT, UTCCP
// Using the same pattern as tcgen05_encoding_soup.cu that compiles cleanly.
// ================================================================
extern "C" __global__ void k_tcgen05_sync(uint64_t *out, uint64_t desc_a, uint64_t desc_b,
                                           uint64_t idesc_val, uint64_t nCols) {
    __shared__ alignas(8) unsigned long long mbar;
    asm volatile(
        "{\n\t"
        ".reg .pred p0;\n\t"
        ".reg .b32 tmem_addr, r0;\n\t"

        // UTCFENCE — fence before thread sync
        "tcgen05.fence::before_thread_sync;\n\t"

        // MMA — reuse alloc pattern from known-good soup
        "tcgen05.alloc.cta_group::1.sync.aligned.shared::cta.b32 [%5], %4;\n\t"
        "tcgen05.relinquish_alloc_permit.cta_group::1.sync.aligned;\n\t"
        "ld.shared.b32 tmem_addr, [%5];\n\t"

        "tcgen05.mma.cta_group::1.kind::f16 [tmem_addr], %1, %2, %3, p0;\n\t"

        // UTCCOMMIT — commit to mbarrier
        "tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%6];\n\t"

        // UTCFENCE — fence after thread sync
        "tcgen05.fence::after_thread_sync;\n\t"

        // UTCWAIT — wait for ld
        "tcgen05.wait::ld.sync.aligned;\n\t"

        // tcgen05.ld
        "tcgen05.ld.sync.aligned.32x32b.x1.b32 {r0}, [tmem_addr];\n\t"

        // UTCWAIT — wait for st
        "tcgen05.wait::st.sync.aligned;\n\t"

        // tcgen05.st
        "tcgen05.st.sync.aligned.32x32b.x1.b32 [tmem_addr], {r0};\n\t"

        // dealloc
        "tcgen05.dealloc.cta_group::1.sync.aligned.b32 tmem_addr, %4;\n\t"

        "st.global.b32 [%0], r0;\n\t"
        "}\n\t"
        :
        : "l"(out), "l"(desc_a), "l"(desc_b), "r"((uint32_t)idesc_val),
          "r"((uint32_t)nCols),
          "r"((unsigned)__cvta_generic_to_shared((void*)out)),
          "r"((unsigned)__cvta_generic_to_shared(&mbar))
        : "memory"
    );
}

// UTCCP — tcgen05.cp has strict shape/type requirements; encoding captured from
// the tcgen05_encoding_soup.cu which already exercises the shape variants.
// Skip standalone kernel to avoid complex shape validation.

// ================================================================
// SETMAXNREG — dynamic register reallocation
// ================================================================
__global__ __launch_bounds__(128, 2)
void k_setmaxnreg_v1(float* out) {
    int warp_id = threadIdx.x / 32;
    if (warp_id < 2) {
        asm volatile("setmaxnreg.inc.sync.aligned.u32 40;");
        out[threadIdx.x] = (float)threadIdx.x;
    } else {
        asm volatile("setmaxnreg.dec.sync.aligned.u32 40;");
        out[threadIdx.x + 128] = (float)threadIdx.x;
    }
}

__global__ __launch_bounds__(256, 1)
void k_setmaxnreg_v2(float* out) {
    int warp_id = threadIdx.x / 32;
    if (warp_id < 4) {
        asm volatile("setmaxnreg.inc.sync.aligned.u32 48;");
        out[threadIdx.x] = (float)(threadIdx.x * 2);
    } else {
        asm volatile("setmaxnreg.dec.sync.aligned.u32 48;");
        out[threadIdx.x + 256] = (float)(threadIdx.x * 3);
    }
}

// VMAD — emulated via IMAD on sm_70+; skip inline asm
__device__ __noinline__ int vmad_ops(int a, int b, int c) {
    return a * b + c;
}

// ================================================================
// UREDUX — uniform redux
// ================================================================
__device__ __noinline__ unsigned uredux_ops(unsigned val) {
    unsigned r1, r2;
    r1 = __reduce_add_sync(0xffffffff, (int)val);
    r2 = __reduce_or_sync(0xffffffff, val);
    return r1 + r2;
}

// ================================================================
// Additional register diversity for existing keys
// ================================================================
__device__ __noinline__ float ffma_variety(float a, float b, float c, float d, float e, float f) {
    float r = fmaf(a, b, c);
    r = fmaf(d, e, f);
    r = fmaf(a, d, r);
    r = fmaf(b, e, r);
    r = fmaf(c, f, r);
    return r;
}

__device__ __noinline__ int iadd3_variety(int a, int b, int c, int d, int e, int f) {
    return (a + b + c) + (d + e + f);
}

__device__ __noinline__ void ldg_stg_variety(float* out, const float* in, int idx) {
    // 8-byte
    double v = *(double*)(in + idx);
    *(double*)(out + idx) = v;
    // 16-byte
    float4 v4 = *(float4*)(in + idx + 4);
    *(float4*)(out + idx + 4) = v4;
    // Single byte/short
    char c = *((char*)in + idx);
    *((char*)out + idx + 8) = c;
    short s = *((short*)in + idx);
    *((short*)out + idx + 10) = s;
}

__device__ __noinline__ void shf_variety(unsigned* out, unsigned a, unsigned b) {
    unsigned r;
    asm volatile("shf.l.wrap.b32 %0, %1, %2, 4;" : "=r"(r) : "r"(a), "r"(b));
    out[0] = r;
    asm volatile("shf.r.wrap.b32 %0, %1, %2, 8;" : "=r"(r) : "r"(a), "r"(b));
    out[1] = r;
    asm volatile("shf.l.clamp.b32 %0, %1, %2, 12;" : "=r"(r) : "r"(a), "r"(b));
    out[2] = r;
    asm volatile("shf.r.clamp.b32 %0, %1, %2, 16;" : "=r"(r) : "r"(a), "r"(b));
    out[3] = r;
    // 64-bit shifts
    unsigned hi, lo;
    asm volatile("shf.l.wrap.b32 %0, %1, %2, %3;" : "=r"(hi) : "r"(a), "r"(b), "r"(3u));
    asm volatile("shf.r.wrap.b32 %0, %1, %2, %3;" : "=r"(lo) : "r"(a), "r"(b), "r"(5u));
    out[4] = hi + lo;
}

// ================================================================
// Main kernel — call all gap-filling functions
// ================================================================
extern "C" __global__ void gap_filler_main(
    float* __restrict__ fout, int* __restrict__ iout,
    double* __restrict__ dout, const float* __restrict__ fin,
    int n)
{
    __shared__ alignas(8) unsigned long long smem_mbar[2];
    int t = threadIdx.x + blockIdx.x * blockDim.x;

    // BFE / BFI
    unsigned bfe_r = bfe_ops((unsigned)t, (unsigned)(t+1), (unsigned)(t+2));
    unsigned bfi_r = bfi_ops((unsigned)t, (unsigned)(t+1), (unsigned)(t+2));

    // DMNMX
    double dm = dmnmx_ops((double)t, (double)(t + 1));

    // FMNMX3 / IMNMX3
    float fm3 = fmnmx3_ops((float)t, (float)(t+1), (float)(t+2));
    int im3 = imnmx3_ops(t, t+1, t+2);

    // JMP (indexed branch)
    int jmp_r = jmp_ops(t);

    // LDU
    float ldu_r = ldu_ops(fin, t & 255);

    // MBAR
    if (threadIdx.x == 0) {
        mbar_ops(smem_mbar);
    }
    __syncthreads();

    // VMAD
    int vmad_r = vmad_ops(t, t+1, t+2);

    // UREDUX
    unsigned uredux_r = uredux_ops((unsigned)t);

    // Register diversity
    float fv = ffma_variety((float)t, (float)(t+1), (float)(t+2),
                            (float)(t+3), (float)(t+4), (float)(t+5));
    int iv = iadd3_variety(t, t+1, t+2, t+3, t+4, t+5);

    // LDG/STG diversity
    ldg_stg_variety(fout + 512, fin + 512, t & 63);

    // SHF diversity
    unsigned shf_out[5];
    shf_variety(shf_out, (unsigned)t, (unsigned)(t+1));

    // Store
    fout[t] = fv + fm3 + ldu_r + (float)bfe_r + (float)bfi_r;
    iout[t] = iv + im3 + jmp_r + vmad_r + (int)uredux_r + (int)shf_out[0];
    dout[t] = dm;
}
